### ISSUE TITLE
[A1111 v1.8.0] Dosen't Work ? ... Oh no it works ! just restart 3 time

### ISSUE THREAD

**Issue by zopi4k** [John-WL/sd-webui-inpaint-difference#18] opened 2024-03-02 14:09 UTC
Hello John-WL, 

For my part, Sd-webui-inpaint-difference is my favorit tool to create quickly a mask, but this morning I have pass on the A1111 v1.8.0 but the Inpaint-difference panel has disappeared. It's normal ? Or I have miss the update ? Just I whant know if I am the only one in the truble ^.^'

**Comment by zopi4k** [comment] 2024-03-02 14:19
Ho ... its work ! ... I have restart 3 time the A1111 Webui ... so strange ... sorry ^.^'

**Comment by John-WL** [comment] 2024-03-02 21:57
Oh 1.8 is out! I'll check on my side if I can reproduce, I haven't updated it yet.

**Comment by John-WL** [comment] 2024-03-03 04:29
I felt like I had to refactor a bit the parameters (UI only) because of the new "soft inpainting" section. The new "difference threshold" slider has apparently nothing to do with the slider that has the same name in this extension. Nesting them each in their own accordion seems like the natural thing to do. 

I really liked how the previous UI flowed with the existing UI params, but I would rather not make it more confusing than it already is. 

I've tested it, the update doesn't seem to have broken the extension, so I'll close the issue.

**Closed by John-WL** 2024-03-03 04:29 UTC
