### ISSUE TITLE
Unique elem_id is a problem

### ISSUE THREAD

**Issue by light-and-ray** [John-WL/sd-webui-inpaint-difference#8] opened 2024-01-06 03:09 UTC
Hello, I've made an [extension](https://github.com/light-and-ray/sd-webui-lama-cleaner-masked-content), which changes "Masked content" option in img2img tab. And I've noticed it doesn't apply on your extension tab, because your "Masked content" has different elem_id. `inpaint_difference_inpainting_fill` instend of `img2img_inpainting_fill` The same with other options which you share with regular inpaint

It's not problem for my extension, I can add your elem_id in my list. But it's not logical for my opinion, because it is the same img2img tab, and these options are used in the same img2img pipline. Maybe someone else want to change something in inpaint, and it wont apply to your tab

P.s. I want to say, your extension is amazing :) I use it in pair with "upscaler for img2img" from extra options, to simulate hires fix to avoid blurred inpainted images

**Comment by John-WL** [comment] 2024-01-06 08:15
Yeay, I'm glad the extension has been useful to you! 

I don't think it's a good idea duplicate elem_ids because they are supposed to be unique. If I change it to be the same as the other tab, it could create other issues. 

Is there a way to implement your feature in a more scalable manner? I realized that the end of the string for the elem_ids is always "[placeholder]_inpainting_fill", so that's why the elem_id I added ends with "inpainting_fill". 

I think a better way to handle this would be to search for all the blocks under the img2img tab, check for the elem_ids that match a certain regex, and hope all extensions add elem_ids with the proper string endings. 

What do you think?

**Comment by John-WL** [comment] 2024-01-06 08:38
I think the optimal solution would be for this extension to reuse the same sliders and buttons that are already created for the inpinting tab, but the problem is that I need to hide the alpha slider in the tab, and I found that it creates a lot of coupling between the webui and this extension when I reuse the existing slider/button components. 

The webui does not provide a clean way to extend the img2img tab right now, so I wanted to write code that I wouldn't need to maintain too often.

**Comment by John-WL** [comment] 2024-01-06 09:03
> I thought yes, this fileld is supposed it be unique

Yeah, nevermind, I think this sums up the issue. You're right, it should be the same elem_id. In theory, it's the same exact component, but I'm duplicating it because the webui won't easily let me implement this. 

I'll try to make a component for reusing the inpaint params in a way that won't break easily.

**Comment by John-WL** [comment] 2024-01-06 09:32
Like you said, simply duplicating elem_ids could potentially work for your usecase, but it feels wrong because in practice, they are duplicated. If an extension requires a reference to only one component with that elem_id for whatever reason (it's a reasonable assumption to make), it's gonna break there.

**Comment by John-WL** [comment] 2024-01-07 23:55
Should be fixed, let me know if there's still a problem!

**Closed** 2024-01-07 23:55 UTC
